In [1]:
#!pip install "flaml[catboost]"

Collecting flaml[catboost]
  Downloading FLAML-2.3.1-py3-none-any.whl.metadata (16 kB)
Requirement already satisfied: NumPy>=1.17 in c:\users\5-05\miniforge3\envs\fintech\lib\site-packages (from flaml[catboost]) (1.26.4)
Collecting catboost<1.2,>=0.26 (from flaml[catboost])
  Downloading catboost-1.1.1-cp310-none-win_amd64.whl.metadata (1.2 kB)
Requirement already satisfied: graphviz in c:\users\5-05\miniforge3\envs\fintech\lib\site-packages (from catboost<1.2,>=0.26->flaml[catboost]) (0.20.3)
Requirement already satisfied: matplotlib in c:\users\5-05\miniforge3\envs\fintech\lib\site-packages (from catboost<1.2,>=0.26->flaml[catboost]) (3.9.1.post1)
Requirement already satisfied: pandas>=0.24.0 in c:\users\5-05\miniforge3\envs\fintech\lib\site-packages (from catboost<1.2,>=0.26->flaml[catboost]) (2.2.2)
Requirement already satisfied: scipy in c:\users\5-05\miniforge3\envs\fintech\lib\site-packages (from catboost<1.2,>=0.26->flaml[catboost]) (1.13.1)
Requirement already satisfied: plotly in c:\users\5-05\miniforge3\envs\fintech\lib\site-packages (from catboost<1.2,>=0.26->flaml[catboost]) (5.24.1)
Requirement already satisfied: six in c:\users\5-05\miniforge3\envs\fintech\lib\site-packages (from catboost<1.2,>=0.26->flaml[catboost]) (1.16.0)
Requirement already satisfied: python-dateutil>=2.8.2 in c:\users\5-05\miniforge3\envs\fintech\lib\site-packages (from pandas>=0.24.0->catboost<1.2,>=0.26->flaml[catboost]) (2.9.0)
Requirement already satisfied: pytz>=2020.1 in c:\users\5-05\miniforge3\envs\fintech\lib\site-packages (from pandas>=0.24.0->catboost<1.2,>=0.26->flaml[catboost]) (2024.1)
Requirement already satisfied: tzdata>=2022.7 in c:\users\5-05\miniforge3\envs\fintech\lib\site-packages (from pandas>=0.24.0->catboost<1.2,>=0.26->flaml[catboost]) (2024.1)
Requirement already satisfied: contourpy>=1.0.1 in c:\users\5-05\miniforge3\envs\fintech\lib\site-packages (from matplotlib->catboost<1.2,>=0.26->flaml[catboost]) (1.2.1)
Requirement already satisfied: cycler>=0.10 in c:\users\5-05\miniforge3\envs\fintech\lib\site-packages (from matplotlib->catboost<1.2,>=0.26->flaml[catboost]) (0.12.1)
Requirement already satisfied: fonttools>=4.22.0 in c:\users\5-05\miniforge3\envs\fintech\lib\site-packages (from matplotlib->catboost<1.2,>=0.26->flaml[catboost]) (4.53.1)
Requirement already satisfied: kiwisolver>=1.3.1 in c:\users\5-05\miniforge3\envs\fintech\lib\site-packages (from matplotlib->catboost<1.2,>=0.26->flaml[catboost]) (1.4.5)
Requirement already satisfied: packaging>=20.0 in c:\users\5-05\miniforge3\envs\fintech\lib\site-packages (from matplotlib->catboost<1.2,>=0.26->flaml[catboost]) (24.1)
Requirement already satisfied: pillow>=8 in c:\users\5-05\miniforge3\envs\fintech\lib\site-packages (from matplotlib->catboost<1.2,>=0.26->flaml[catboost]) (10.4.0)
Requirement already satisfied: pyparsing>=2.3.1 in c:\users\5-05\miniforge3\envs\fintech\lib\site-packages (from matplotlib->catboost<1.2,>=0.26->flaml[catboost]) (3.1.2)
Requirement already satisfied: tenacity>=6.2.0 in c:\users\5-05\miniforge3\envs\fintech\lib\site-packages (from plotly->catboost<1.2,>=0.26->flaml[catboost]) (8.5.0)
Downloading catboost-1.1.1-cp310-none-win_amd64.whl (73.9 MB)
   ---------------------------------------- 0.0/73.9 MB ? eta -:--:--
   ---------------------------------------- 0.0/73.9 MB 960.0 kB/s eta 0:01:17
    --------------------------------------- 1.4/73.9 MB 18.1 MB/s eta 0:00:05
   -- ------------------------------------- 5.5/73.9 MB 44.1 MB/s eta 0:00:02
   ----- ---------------------------------- 10.3/73.9 MB 81.8 MB/s eta 0:00:01
   -------- ------------------------------- 14.8/73.9 MB 93.9 MB/s eta 0:00:01
   --------- ------------------------------ 18.1/73.9 MB 81.8 MB/s eta 0:00:01
   ---------- ----------------------------- 19.9/73.9 MB 72.6 MB/s eta 0:00:01
   ----------- ---------------------------- 22.1/73.9 MB 65.6 MB/s eta 0:00:01
   ------------ --------------------------- 22.3/73.9 MB 46.7 MB/s eta 0:00:02
   ------------ --------------------------- 22.5/73.9 MB 38.6 MB/s eta 0:00:02
   ------------ --------------------------- 24.0/73.9 MB 34.4 MB/s eta 0:00:02
   ------------- -------------------------- 24.4/73.9 MB 31.2 MB/s eta 0:00:02
   ------------- -------------------------- 24.9/73.9 MB 27.3 MB/s eta 0:00:02
   -------------- ------------------------- 26.4/73.9 MB 25.2 MB/s eta 0:00:02
   -------------- ------------------------- 26.8/73.9 MB 22.6 MB/s eta 0:00:03
   ---------------- ----------------------- 29.9/73.9 MB 24.2 MB/s eta 0:00:02
   ---------------- ----------------------- 30.6/73.9 MB 21.8 MB/s eta 0:00:02
   ---------------- ----------------------- 31.0/73.9 MB 20.5 MB/s eta 0:00:03
   ----------------- ---------------------- 33.2/73.9 MB 26.2 MB/s eta 0:00:02
   ------------------- -------------------- 36.8/73.9 MB 40.9 MB/s eta 0:00:01
   ------------------- -------------------- 36.9/73.9 MB 34.4 MB/s eta 0:00:02
   -------------------- ------------------- 37.1/73.9 MB 31.2 MB/s eta 0:00:02
   -------------------- ------------------- 37.3/73.9 MB 28.4 MB/s eta 0:00:02
   -------------------- ------------------- 38.1/73.9 MB 26.2 MB/s eta 0:00:02
   --------------------- ------------------ 40.0/73.9 MB 25.2 MB/s eta 0:00:02
   --------------------- ------------------ 40.0/73.9 MB 23.4 MB/s eta 0:00:02
   --------------------- ------------------ 40.1/73.9 MB 19.9 MB/s eta 0:00:02
   --------------------- ------------------ 40.4/73.9 MB 18.2 MB/s eta 0:00:02
   ---------------------- ----------------- 40.8/73.9 MB 17.7 MB/s eta 0:00:02
   ------------------------ --------------- 45.2/73.9 MB 20.5 MB/s eta 0:00:02
   -------------------------- ------------- 49.2/73.9 MB 31.2 MB/s eta 0:00:01
   ---------------------------- ----------- 52.6/73.9 MB 81.8 MB/s eta 0:00:01
   ---------------------------- ----------- 52.8/73.9 MB 59.5 MB/s eta 0:00:01
   ---------------------------- ----------- 53.4/73.9 MB 46.9 MB/s eta 0:00:01
   ----------------------------- ---------- 55.4/73.9 MB 43.7 MB/s eta 0:00:01
   -------------------------------- ------- 59.6/73.9 MB 43.7 MB/s eta 0:00:01
   --------------------------------- ------ 62.8/73.9 MB 43.7 MB/s eta 0:00:01
   ------------------------------------ --- 67.1/73.9 MB 81.8 MB/s eta 0:00:01
   -------------------------------------- - 72.0/73.9 MB 93.0 MB/s eta 0:00:01
   ---------------------------------------  73.9/73.9 MB 93.9 MB/s eta 0:00:01
   ---------------------------------------  73.9/73.9 MB 93.9 MB/s eta 0:00:01
   ---------------------------------------  73.9/73.9 MB 93.9 MB/s eta 0:00:01
   ---------------------------------------  73.9/73.9 MB 93.9 MB/s eta 0:00:01
   ---------------------------------------  73.9/73.9 MB 93.9 MB/s eta 0:00:01
   ---------------------------------------- 73.9/73.9 MB 31.2 MB/s eta 0:00:00
Downloading FLAML-2.3.1-py3-none-any.whl (313 kB)
   ---------------------------------------- 0.0/313.3 kB ? eta -:--:--
   ---------------------------------------- 313.3/313.3 kB ? eta 0:00:00
Installing collected packages: flaml, catboost
Successfully installed catboost-1.1.1 flaml-2.3.1

In [2]:
import warnings
warnings.filterwarnings(action='ignore')

# 밑에 실행하면서 뜨는 빨간 경고 팝업 뜨지 않게 하기

In [4]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
import koreanize_matplotlib   # 한국어 출력되게
import os
import chart_studio.plotly as py
from plotly.offline import init_notebook_mode, iplot
init_notebook_mode(connected = True)
import plotly.graph_objs as go
import pmdarima as pm
from pmdarima.arima import ndiffs
# autogluon.tabular import TabularPredictor

In [5]:
# 깃허브에서 'titanic' 데이터 바로 연동시키기

data = pd.read_csv("https://raw.githubusercontent.com/haram4th/ablearn/main/Taitanic_train.csv")
data

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S
...,...,...,...,...,...,...,...,...,...,...,...,...
886,887,0,2,"Montvila, Rev. Juozas",male,27.0,0,0,211536,13.0000,NaN,S
887,888,1,1,"Graham, Miss. Margaret Edith",female,19.0,0,0,112053,30.0000,B42,S
888,889,0,3,"Johnston, Miss. Catherine Helen ""Carrie""",female,NaN,1,2,W./C. 6607,23.4500,NaN,S
889,890,1,1,"Behr, Mr. Karl Howell",male,26.0,0,0,111369,30.0000,C148,C
890,891,0,3,"Dooley, Mr. Patrick",male,32.0,0,0,370376,7.7500,NaN,Q

In [ ]:
train_data = data.dropna()
target_column = 'is_fraud'

model = TabularPredictor(label=target_column).fit(train_data)
test_data = train_data.sample(frac=0.2, random_state=10)
pred = model.predict(test_data)

print("Train Score:", model.evaluate(test_data))
print("best model: ", model.get_model_best())