In [3]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

In [4]:
data = pd.read_csv("../06machine_learning/data/house_test.csv")
data

,Id,MSSubClass,MSZoning,LotFrontage,LotArea,Street,Alley,LotShape,LandContour,Utilities,...,ScreenPorch,PoolArea,PoolQC,Fence,MiscFeature,MiscVal,MoSold,YrSold,SaleType,SaleCondition
0,1461,20,RH,80.0,11622,Pave,NaN,Reg,Lvl,AllPub,...,120,0,NaN,MnPrv,NaN,0,6,2010,WD,Normal
1,1462,20,RL,81.0,14267,Pave,NaN,IR1,Lvl,AllPub,...,0,0,NaN,NaN,Gar2,12500,6,2010,WD,Normal
2,1463,60,RL,74.0,13830,Pave,NaN,IR1,Lvl,AllPub,...,0,0,NaN,MnPrv,NaN,0,3,2010,WD,Normal
3,1464,60,RL,78.0,9978,Pave,NaN,IR1,Lvl,AllPub,...,0,0,NaN,NaN,NaN,0,6,2010,WD,Normal
4,1465,120,RL,43.0,5005,Pave,NaN,IR1,HLS,AllPub,...,144,0,NaN,NaN,NaN,0,1,2010,WD,Normal
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1454,2915,160,RM,21.0,1936,Pave,NaN,Reg,Lvl,AllPub,...,0,0,NaN,NaN,NaN,0,6,2006,WD,Normal
1455,2916,160,RM,21.0,1894,Pave,NaN,Reg,Lvl,AllPub,...,0,0,NaN,NaN,NaN,0,4,2006,WD,Abnorml
1456,2917,20,RL,160.0,20000,Pave,NaN,Reg,Lvl,AllPub,...,0,0,NaN,NaN,NaN,0,9,2006,WD,Abnorml
1457,2918,85,RL,62.0,10441,Pave,NaN,Reg,Lvl,AllPub,...,0,0,NaN,MnPrv,Shed,700,7,2006,WD,Normal
1458,2919,60,RL,74.0,9627,Pave,NaN,Reg,Lvl,AllPub,...,0,0,NaN,NaN,NaN,0,11,2006,WD,Normal

In [5]:
data3 = data.copy()

In [6]:
data = pd.get_dummies(data)
data

,Id,MSSubClass,LotFrontage,LotArea,OverallQual,OverallCond,YearBuilt,YearRemodAdd,MasVnrArea,BsmtFinSF1,...,SaleType_ConLw,SaleType_New,SaleType_Oth,SaleType_WD,SaleCondition_Abnorml,SaleCondition_AdjLand,SaleCondition_Alloca,SaleCondition_Family,SaleCondition_Normal,SaleCondition_Partial
0,1461,20,80.0,11622,5,6,1961,1961,0.0,468.0,...,False,False,False,True,False,False,False,False,True,False
1,1462,20,81.0,14267,6,6,1958,1958,108.0,923.0,...,False,False,False,True,False,False,False,False,True,False
2,1463,60,74.0,13830,5,5,1997,1998,0.0,791.0,...,False,False,False,True,False,False,False,False,True,False
3,1464,60,78.0,9978,6,6,1998,1998,20.0,602.0,...,False,False,False,True,False,False,False,False,True,False
4,1465,120,43.0,5005,8,5,1992,1992,0.0,263.0,...,False,False,False,True,False,False,False,False,True,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1454,2915,160,21.0,1936,4,7,1970,1970,0.0,0.0,...,False,False,False,True,False,False,False,False,True,False
1455,2916,160,21.0,1894,4,5,1970,1970,0.0,252.0,...,False,False,False,True,True,False,False,False,False,False
1456,2917,20,160.0,20000,5,7,1960,1996,0.0,1224.0,...,False,False,False,True,True,False,False,False,False,False
1457,2918,85,62.0,10441,5,5,1992,1992,0.0,337.0,...,False,False,False,True,False,False,False,False,True,False
1458,2919,60,74.0,9627,7,5,1993,1994,94.0,758.0,...,False,False,False,True,False,False,False,False,True,False

In [7]:
data = data[['OverallQual', 'GrLivArea', 'GarageCars', 'YearBuilt', 'FullBath',
       'TotalBsmtSF', '1stFlrSF', 'ExterQual_Gd', 'YearRemodAdd', 'Fireplaces',
       'KitchenQual_TA', 'GarageFinish_Unf', 'ExterQual_TA']]

In [8]:
data

,OverallQual,GrLivArea,GarageCars,YearBuilt,FullBath,TotalBsmtSF,1stFlrSF,ExterQual_Gd,YearRemodAdd,Fireplaces,KitchenQual_TA,GarageFinish_Unf,ExterQual_TA
0,5,896,1.0,1961,1,882.0,896,False,1961,0,True,True,True
1,6,1329,1.0,1958,1,1329.0,1329,False,1958,0,False,True,True
2,5,1629,2.0,1997,2,928.0,928,False,1998,1,True,False,True
3,6,1604,2.0,1998,2,926.0,926,False,1998,1,False,False,True
4,8,1280,2.0,1992,2,1280.0,1280,True,1992,0,False,False,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...
1454,4,1092,0.0,1970,1,546.0,546,False,1970,0,True,False,True
1455,4,1092,1.0,1970,1,546.0,546,False,1970,0,True,True,True
1456,5,1224,2.0,1960,1,1224.0,1224,False,1996,1,True,True,True
1457,5,970,0.0,1992,1,912.0,970,False,1992,0,True,False,True
1458,7,2000,3.0,1993,2,996.0,996,False,1994,1,True,False,True

In [9]:
import joblib

In [10]:
rs = joblib.load("./model/iowa_robustscaler.joblib")
data_scaled = rs.transform(data)
data_scaled = pd.DataFrame(data_scaled, columns=data.columns)
data_scaled

,OverallQual,GrLivArea,GarageCars,YearBuilt,FullBath,TotalBsmtSF,1stFlrSF,ExterQual_Gd,YearRemodAdd,Fireplaces,KitchenQual_TA,GarageFinish_Unf,ExterQual_TA
0,-0.5,-0.877559,-1.0,-0.260870,-1.0,-0.217910,-0.375061,0.0,-0.891892,-1.0,0.0,1.0,0.0
1,0.0,-0.208575,-1.0,-0.326087,-1.0,0.671642,0.475209,0.0,-0.972973,-1.0,-1.0,1.0,0.0
2,-0.5,0.254925,0.0,0.521739,0.0,-0.126368,-0.312224,0.0,0.108108,0.0,0.0,0.0,0.0
3,0.0,0.216300,0.0,0.543478,0.0,-0.130348,-0.316151,0.0,0.108108,0.0,-1.0,0.0,0.0
4,1.0,-0.284280,0.0,0.413043,0.0,0.574129,0.378989,1.0,-0.054054,-1.0,-1.0,0.0,-1.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...
1454,-1.0,-0.574739,-2.0,-0.065217,-1.0,-0.886567,-1.062347,0.0,-0.648649,-1.0,0.0,0.0,0.0
1455,-1.0,-0.574739,-1.0,-0.065217,-1.0,-0.886567,-1.062347,0.0,-0.648649,-1.0,0.0,1.0,0.0
1456,-0.5,-0.370800,0.0,-0.282609,-1.0,0.462687,0.269023,0.0,0.054054,0.0,0.0,1.0,0.0
1457,-0.5,-0.763229,-2.0,0.413043,-1.0,-0.158209,-0.229750,0.0,-0.054054,-1.0,0.0,0.0,0.0
1458,0.5,0.828119,1.0,0.434783,0.0,0.008955,-0.178694,0.0,0.000000,0.0,0.0,0.0,0.0

In [11]:
from tensorflow.keras.models import load_model

2024-09-12 10:25:57.792090: I tensorflow/core/platform/cpu_feature_guard.cc:193] This TensorFlow binary is optimized with oneAPI Deep Neural Network Library (oneDNN) to use the following CPU instructions in performance-critical operations:  AVX2 FMA
To enable them in other operations, rebuild TensorFlow with the appropriate compiler flags.
2024-09-12 10:25:59.208020: I tensorflow/c/logging.cc:34] Successfully opened dynamic library libdirectml.d6f03b303ac3c4f2eeb8ca631688c9757b361310.so
2024-09-12 10:25:59.208198: I tensorflow/c/logging.cc:34] Successfully opened dynamic library libdxcore.so
2024-09-12 10:25:59.211883: I tensorflow/c/logging.cc:34] Successfully opened dynamic library libd3d12.so
2024-09-12 10:25:59.438335: I tensorflow/c/logging.cc:34] DirectML device enumeration: found 1 compatible adapters.

In [12]:
model = load_model("./model/iowa_house792__925173184.0000.keras")
pred = model.predict(data_scaled)
pred = pd.DataFrame(pred, columns=['test_pred'])
pred

2024-09-12 10:25:59.652323: I tensorflow/core/platform/cpu_feature_guard.cc:193] This TensorFlow binary is optimized with oneAPI Deep Neural Network Library (oneDNN) to use the following CPU instructions in performance-critical operations:  AVX2 FMA
To enable them in other operations, rebuild TensorFlow with the appropriate compiler flags.
2024-09-12 10:25:59.653463: I tensorflow/c/logging.cc:34] DirectML: creating device on adapter 0 (AMD Radeon(TM) RX Vega 11 Graphics)
2024-09-12 10:25:59.825022: I tensorflow/core/common_runtime/pluggable_device/pluggable_device_factory.cc:306] Could not identify NUMA node of platform GPU ID 0, defaulting to 0. Your kernel may not have been built with NUMA support.
2024-09-12 10:25:59.825072: W tensorflow/core/common_runtime/pluggable_device/pluggable_device_bfc_allocator.cc:28] Overriding allow_growth setting because force_memory_growth was requested by the device.
2024-09-12 10:25:59.825095: I tensorflow/core/common_runtime/pluggable_device/pluggable_device_factory.cc:272] Created TensorFlow device (/job:localhost/replica:0/task:0/device:GPU:0 with 15603 MB memory) -> physical PluggableDevice (device: 0, name: DML, pci bus id: <undefined>)

26/46 [===============>..............] - ETA: 0s

2024-09-12 10:26:00.267120: I tensorflow/core/grappler/optimizers/custom_graph_optimizer_registry.cc:114] Plugin optimizer for device_type GPU is enabled.

46/46 [==============================] - 0s 6ms/step

2024-09-12 10:26:00.620512: I tensorflow/core/common_runtime/pluggable_device/pluggable_device_factory.cc:306] Could not identify NUMA node of platform GPU ID 0, defaulting to 0. Your kernel may not have been built with NUMA support.
2024-09-12 10:26:00.620583: I tensorflow/core/common_runtime/pluggable_device/pluggable_device_factory.cc:272] Created TensorFlow device (/job:localhost/replica:0/task:0/device:GPU:0 with 15603 MB memory) -> physical PluggableDevice (device: 0, name: DML, pci bus id: <undefined>)
2024-09-12 10:26:00.682141: I tensorflow/core/common_runtime/pluggable_device/pluggable_device_factory.cc:306] Could not identify NUMA node of platform GPU ID 0, defaulting to 0. Your kernel may not have been built with NUMA support.
2024-09-12 10:26:00.682225: I tensorflow/core/common_runtime/pluggable_device/pluggable_device_factory.cc:272] Created TensorFlow device (/job:localhost/replica:0/task:0/device:GPU:0 with 15603 MB memory) -> physical PluggableDevice (device: 0, name: DML, pci bus id: <undefined>)
2024-09-12 10:26:00.689508: I tensorflow/core/common_runtime/pluggable_device/pluggable_device_factory.cc:306] Could not identify NUMA node of platform GPU ID 0, defaulting to 0. Your kernel may not have been built with NUMA support.
2024-09-12 10:26:00.689749: I tensorflow/core/common_runtime/pluggable_device/pluggable_device_factory.cc:272] Created TensorFlow device (/job:localhost/replica:0/task:0/device:GPU:0 with 15603 MB memory) -> physical PluggableDevice (device: 0, name: DML, pci bus id: <undefined>)

          test_pred
0     109955.562500
1     146410.140625
2     167009.890625
3     195284.078125
4     200004.109375
...             ...
1454  113808.890625
1455  108089.812500
1456  139701.765625
1457  128684.101562
1458  239234.031250

[1459 rows x 1 columns]

# 함수로 테스트 데이터 처리하기

In [13]:
def data_preporcessing(data):
    data = pd.get_dummies(data)
    data = data[['OverallQual', 'GrLivArea', 'GarageCars', 'YearBuilt', 'FullBath',
       'TotalBsmtSF', '1stFlrSF', 'ExterQual_Gd', 'YearRemodAdd', 'Fireplaces',
       'KitchenQual_TA', 'GarageFinish_Unf', 'ExterQual_TA']]
    rs = joblib.load("./model/iowa_robustscaler.joblib")
    data_scaled = rs.transform(data)
    data_scaled = pd.DataFrame(data_scaled, columns=data.columns)
    return data_scaled

In [14]:
def prediction(data):
    model = load_model("./model/iowa_house792__925173184.0000.keras")
    pred = model.predict(data)
    pred = pd.DataFrame(pred, columns=['test_pred'])
    return pred

In [15]:
data2 = pd.read_csv("../06machine_learning/data/house_test.csv")
result = data_preporcessing(data2)
result

,OverallQual,GrLivArea,GarageCars,YearBuilt,FullBath,TotalBsmtSF,1stFlrSF,ExterQual_Gd,YearRemodAdd,Fireplaces,KitchenQual_TA,GarageFinish_Unf,ExterQual_TA
0,-0.5,-0.877559,-1.0,-0.260870,-1.0,-0.217910,-0.375061,0.0,-0.891892,-1.0,0.0,1.0,0.0
1,0.0,-0.208575,-1.0,-0.326087,-1.0,0.671642,0.475209,0.0,-0.972973,-1.0,-1.0,1.0,0.0
2,-0.5,0.254925,0.0,0.521739,0.0,-0.126368,-0.312224,0.0,0.108108,0.0,0.0,0.0,0.0
3,0.0,0.216300,0.0,0.543478,0.0,-0.130348,-0.316151,0.0,0.108108,0.0,-1.0,0.0,0.0
4,1.0,-0.284280,0.0,0.413043,0.0,0.574129,0.378989,1.0,-0.054054,-1.0,-1.0,0.0,-1.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...
1454,-1.0,-0.574739,-2.0,-0.065217,-1.0,-0.886567,-1.062347,0.0,-0.648649,-1.0,0.0,0.0,0.0
1455,-1.0,-0.574739,-1.0,-0.065217,-1.0,-0.886567,-1.062347,0.0,-0.648649,-1.0,0.0,1.0,0.0
1456,-0.5,-0.370800,0.0,-0.282609,-1.0,0.462687,0.269023,0.0,0.054054,0.0,0.0,1.0,0.0
1457,-0.5,-0.763229,-2.0,0.413043,-1.0,-0.158209,-0.229750,0.0,-0.054054,-1.0,0.0,0.0,0.0
1458,0.5,0.828119,1.0,0.434783,0.0,0.008955,-0.178694,0.0,0.000000,0.0,0.0,0.0,0.0

In [16]:
prediction(result)

46/46 [==============================] - 0s 4ms/step

2024-09-12 10:26:01.189576: I tensorflow/core/grappler/optimizers/custom_graph_optimizer_registry.cc:114] Plugin optimizer for device_type GPU is enabled.

          test_pred
0     109955.562500
1     146410.140625
2     167009.890625
3     195284.078125
4     200004.109375
...             ...
1454  113808.890625
1455  108089.812500
1456  139701.765625
1457  128684.101562
1458  239234.031250

[1459 rows x 1 columns]

# XGBR 모델 불러와서 분석하기

In [17]:
data3 = pd.read_csv("../06machine_learning/data/house_test.csv")

In [18]:
data3.columns

Index(['Id', 'MSSubClass', 'MSZoning', 'LotFrontage', 'LotArea', 'Street',
       'Alley', 'LotShape', 'LandContour', 'Utilities', 'LotConfig',
       'LandSlope', 'Neighborhood', 'Condition1', 'Condition2', 'BldgType',
       'HouseStyle', 'OverallQual', 'OverallCond', 'YearBuilt', 'YearRemodAdd',
       'RoofStyle', 'RoofMatl', 'Exterior1st', 'Exterior2nd', 'MasVnrType',
       'MasVnrArea', 'ExterQual', 'ExterCond', 'Foundation', 'BsmtQual',
       'BsmtCond', 'BsmtExposure', 'BsmtFinType1', 'BsmtFinSF1',
       'BsmtFinType2', 'BsmtFinSF2', 'BsmtUnfSF', 'TotalBsmtSF', 'Heating',
       'HeatingQC', 'CentralAir', 'Electrical', '1stFlrSF', '2ndFlrSF',
       'LowQualFinSF', 'GrLivArea', 'BsmtFullBath', 'BsmtHalfBath', 'FullBath',
       'HalfBath', 'BedroomAbvGr', 'KitchenAbvGr', 'KitchenQual',
       'TotRmsAbvGrd', 'Functional', 'Fireplaces', 'FireplaceQu', 'GarageType',
       'GarageYrBlt', 'GarageFinish', 'GarageCars', 'GarageArea', 'GarageQual',
       'GarageCond', 'PavedDrive', 'WoodDeckSF', 'OpenPorchSF',
       'EnclosedPorch', '3SsnPorch', 'ScreenPorch', 'PoolArea', 'PoolQC',
       'Fence', 'MiscFeature', 'MiscVal', 'MoSold', 'YrSold', 'SaleType',
       'SaleCondition'],
      dtype='object')

In [19]:
data3 = data3[['MSSubClass', 'MSZoning', 'LotFrontage', 'LotArea', 'Street',
       'LotShape', 'LandContour', 'Utilities', 'LotConfig', 'LandSlope',
       'Neighborhood', 'Condition1', 'Condition2', 'BldgType', 'HouseStyle',
       'OverallQual', 'OverallCond', 'YearBuilt', 'YearRemodAdd', 'RoofStyle',
       'RoofMatl', 'Exterior1st', 'Exterior2nd', 'MasVnrArea', 'ExterQual',
       'ExterCond', 'Foundation', 'BsmtQual', 'BsmtCond', 'BsmtExposure',
       'BsmtFinType1', 'BsmtFinSF1', 'BsmtFinType2', 'BsmtFinSF2', 'BsmtUnfSF',
       'TotalBsmtSF', 'Heating', 'HeatingQC', 'CentralAir', 'Electrical',
       '1stFlrSF', '2ndFlrSF', 'LowQualFinSF', 'GrLivArea', 'BsmtFullBath',
       'BsmtHalfBath', 'FullBath', 'HalfBath', 'BedroomAbvGr', 'KitchenAbvGr',
       'KitchenQual', 'TotRmsAbvGrd', 'Functional', 'Fireplaces', 'GarageType',
       'GarageYrBlt', 'GarageFinish', 'GarageCars', 'GarageArea', 'GarageQual',
       'GarageCond', 'PavedDrive', 'WoodDeckSF', 'OpenPorchSF',
       'EnclosedPorch', '3SsnPorch', 'ScreenPorch', 'PoolArea', 'MiscVal',
       'MoSold', 'YrSold', 'SaleType', 'SaleCondition']]

In [20]:
data3 = pd.get_dummies(data3)
data3

,MSSubClass,LotFrontage,LotArea,OverallQual,OverallCond,YearBuilt,YearRemodAdd,MasVnrArea,BsmtFinSF1,BsmtFinSF2,...,SaleType_ConLw,SaleType_New,SaleType_Oth,SaleType_WD,SaleCondition_Abnorml,SaleCondition_AdjLand,SaleCondition_Alloca,SaleCondition_Family,SaleCondition_Normal,SaleCondition_Partial
0,20,80.0,11622,5,6,1961,1961,0.0,468.0,144.0,...,False,False,False,True,False,False,False,False,True,False
1,20,81.0,14267,6,6,1958,1958,108.0,923.0,0.0,...,False,False,False,True,False,False,False,False,True,False
2,60,74.0,13830,5,5,1997,1998,0.0,791.0,0.0,...,False,False,False,True,False,False,False,False,True,False
3,60,78.0,9978,6,6,1998,1998,20.0,602.0,0.0,...,False,False,False,True,False,False,False,False,True,False
4,120,43.0,5005,8,5,1992,1992,0.0,263.0,0.0,...,False,False,False,True,False,False,False,False,True,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1454,160,21.0,1936,4,7,1970,1970,0.0,0.0,0.0,...,False,False,False,True,False,False,False,False,True,False
1455,160,21.0,1894,4,5,1970,1970,0.0,252.0,0.0,...,False,False,False,True,True,False,False,False,False,False
1456,20,160.0,20000,5,7,1960,1996,0.0,1224.0,0.0,...,False,False,False,True,True,False,False,False,False,False
1457,85,62.0,10441,5,5,1992,1992,0.0,337.0,0.0,...,False,False,False,True,False,False,False,False,True,False
1458,60,74.0,9627,7,5,1993,1994,94.0,758.0,0.0,...,False,False,False,True,False,False,False,False,True,False

# joblib => 데이터직렬화

In [21]:
X2_columns = joblib.load("./model/X2columns.joblib")
X2_columns

['MSSubClass',
 'LotFrontage',
 'LotArea',
 'OverallQual',
 'OverallCond',
 'YearBuilt',
 'YearRemodAdd',
 'MasVnrArea',
 'BsmtFinSF1',
 'BsmtFinSF2',
 'BsmtUnfSF',
 'TotalBsmtSF',
 '1stFlrSF',
 '2ndFlrSF',
 'LowQualFinSF',
 'GrLivArea',
 'BsmtFullBath',
 'BsmtHalfBath',
 'FullBath',
 'HalfBath',
 'BedroomAbvGr',
 'KitchenAbvGr',
 'TotRmsAbvGrd',
 'Fireplaces',
 'GarageYrBlt',
 'GarageCars',
 'GarageArea',
 'WoodDeckSF',
 'OpenPorchSF',
 'EnclosedPorch',
 '3SsnPorch',
 'ScreenPorch',
 'PoolArea',
 'MiscVal',
 'MoSold',
 'YrSold',
 'MSZoning_C (all)',
 'MSZoning_FV',
 'MSZoning_RH',
 'MSZoning_RL',
 'MSZoning_RM',
 'Street_Grvl',
 'Street_Pave',
 'LotShape_IR1',
 'LotShape_IR2',
 'LotShape_IR3',
 'LotShape_Reg',
 'LandContour_Bnk',
 'LandContour_HLS',
 'LandContour_Low',
 'LandContour_Lvl',
 'Utilities_AllPub',
 'Utilities_NoSeWa',
 'LotConfig_Corner',
 'LotConfig_CulDSac',
 'LotConfig_FR2',
 'LotConfig_FR3',
 'LotConfig_Inside',
 'LandSlope_Gtl',
 'LandSlope_Mod',
 'LandSlope_Sev',
 'Neighborhood_Blmngtn',
 'Neighborhood_Blueste',
 'Neighborhood_BrDale',
 'Neighborhood_BrkSide',
 'Neighborhood_ClearCr',
 'Neighborhood_CollgCr',
 'Neighborhood_Crawfor',
 'Neighborhood_Edwards',
 'Neighborhood_Gilbert',
 'Neighborhood_IDOTRR',
 'Neighborhood_MeadowV',
 'Neighborhood_Mitchel',
 'Neighborhood_NAmes',
 'Neighborhood_NPkVill',
 'Neighborhood_NWAmes',
 'Neighborhood_NoRidge',
 'Neighborhood_NridgHt',
 'Neighborhood_OldTown',
 'Neighborhood_SWISU',
 'Neighborhood_Sawyer',
 'Neighborhood_SawyerW',
 'Neighborhood_Somerst',
 'Neighborhood_StoneBr',
 'Neighborhood_Timber',
 'Neighborhood_Veenker',
 'Condition1_Artery',
 'Condition1_Feedr',
 'Condition1_Norm',
 'Condition1_PosA',
 'Condition1_PosN',
 'Condition1_RRAe',
 'Condition1_RRAn',
 'Condition1_RRNe',
 'Condition1_RRNn',
 'Condition2_Artery',
 'Condition2_Feedr',
 'Condition2_Norm',
 'Condition2_PosA',
 'Condition2_PosN',
 'Condition2_RRAe',
 'Condition2_RRAn',
 'Condition2_RRNn',
 'BldgType_1Fam',
 'BldgType_2fmCon',
 'BldgType_Duplex',
 'BldgType_Twnhs',
 'BldgType_TwnhsE',
 'HouseStyle_1.5Fin',
 'HouseStyle_1.5Unf',
 'HouseStyle_1Story',
 'HouseStyle_2.5Fin',
 'HouseStyle_2.5Unf',
 'HouseStyle_2Story',
 'HouseStyle_SFoyer',
 'HouseStyle_SLvl',
 'RoofStyle_Flat',
 'RoofStyle_Gable',
 'RoofStyle_Gambrel',
 'RoofStyle_Hip',
 'RoofStyle_Mansard',
 'RoofStyle_Shed',
 'RoofMatl_ClyTile',
 'RoofMatl_CompShg',
 'RoofMatl_Membran',
 'RoofMatl_Metal',
 'RoofMatl_Roll',
 'RoofMatl_Tar&Grv',
 'RoofMatl_WdShake',
 'RoofMatl_WdShngl',
 'Exterior1st_AsbShng',
 'Exterior1st_AsphShn',
 'Exterior1st_BrkComm',
 'Exterior1st_BrkFace',
 'Exterior1st_CBlock',
 'Exterior1st_CemntBd',
 'Exterior1st_HdBoard',
 'Exterior1st_ImStucc',
 'Exterior1st_MetalSd',
 'Exterior1st_Plywood',
 'Exterior1st_Stone',
 'Exterior1st_Stucco',
 'Exterior1st_VinylSd',
 'Exterior1st_Wd Sdng',
 'Exterior1st_WdShing',
 'Exterior2nd_AsbShng',
 'Exterior2nd_AsphShn',
 'Exterior2nd_Brk Cmn',
 'Exterior2nd_BrkFace',
 'Exterior2nd_CBlock',
 'Exterior2nd_CmentBd',
 'Exterior2nd_HdBoard',
 'Exterior2nd_ImStucc',
 'Exterior2nd_MetalSd',
 'Exterior2nd_Other',
 'Exterior2nd_Plywood',
 'Exterior2nd_Stone',
 'Exterior2nd_Stucco',
 'Exterior2nd_VinylSd',
 'Exterior2nd_Wd Sdng',
 'Exterior2nd_Wd Shng',
 'ExterQual_Ex',
 'ExterQual_Fa',
 'ExterQual_Gd',
 'ExterQual_TA',
 'ExterCond_Ex',
 'ExterCond_Fa',
 'ExterCond_Gd',
 'ExterCond_Po',
 'ExterCond_TA',
 'Foundation_BrkTil',
 'Foundation_CBlock',
 'Foundation_PConc',
 'Foundation_Slab',
 'Foundation_Stone',
 'Foundation_Wood',
 'BsmtQual_Ex',
 'BsmtQual_Fa',
 'BsmtQual_Gd',
 'BsmtQual_TA',
 'BsmtCond_Fa',
 'BsmtCond_Gd',
 'BsmtCond_Po',
 'BsmtCond_TA',
 'BsmtExposure_Av',
 'BsmtExposure_Gd',
 'BsmtExposure_Mn',
 'BsmtExposure_No',
 'BsmtFinType1_ALQ',
 'BsmtFinType1_BLQ',
 'BsmtFinType1_GLQ',
 'BsmtFinType1_LwQ',
 'BsmtFinType1_Rec',
 'BsmtFinType1_Unf',
 'BsmtFinType2_ALQ',
 'BsmtFinType2_BLQ',
 'BsmtFinType2_GLQ',
 'BsmtFinType2_LwQ',
 'BsmtFinType2_Rec',
 'BsmtFinType2_Unf',
 'Heating_Floor',
 'Heating_GasA',
 'Heating_GasW',
 'Heating_Grav',
 'Heating_OthW',
 'Heating_Wall',
 'HeatingQC_Ex',
 'HeatingQC_Fa',
 'HeatingQC_Gd',
 'HeatingQC_Po',
 'HeatingQC_TA',
 'CentralAir_N',
 'CentralAir_Y',
 'Electrical_FuseA',
 'Electrical_FuseF',
 'Electrical_FuseP',
 'Electrical_Mix',
 'Electrical_SBrkr',
 'KitchenQual_Ex',
 'KitchenQual_Fa',
 'KitchenQual_Gd',
 'KitchenQual_TA',
 'Functional_Maj1',
 'Functional_Maj2',
 'Functional_Min1',
 'Functional_Min2',
 'Functional_Mod',
 'Functional_Sev',
 'Functional_Typ',
 'GarageType_2Types',
 'GarageType_Attchd',
 'GarageType_Basment',
 'GarageType_BuiltIn',
 'GarageType_CarPort',
 'GarageType_Detchd',
 'GarageFinish_Fin',
 'GarageFinish_RFn',
 'GarageFinish_Unf',
 'GarageQual_Ex',
 'GarageQual_Fa',
 'GarageQual_Gd',
 'GarageQual_Po',
 'GarageQual_TA',
 'GarageCond_Ex',
 'GarageCond_Fa',
 'GarageCond_Gd',
 'GarageCond_Po',
 'GarageCond_TA',
 'PavedDrive_N',
 'PavedDrive_P',
 'PavedDrive_Y',
 'SaleType_COD',
 'SaleType_CWD',
 'SaleType_Con',
 'SaleType_ConLD',
 'SaleType_ConLI',
 'SaleType_ConLw',
 'SaleType_New',
 'SaleType_Oth',
 'SaleType_WD',
 'SaleCondition_Abnorml',
 'SaleCondition_AdjLand',
 'SaleCondition_Alloca',
 'SaleCondition_Family',
 'SaleCondition_Normal',
 'SaleCondition_Partial']

In [22]:
for col in X2_columns:
    if col not in data3.columns:
        data3[col] = False

In [23]:
len(data3.columns) == len(X2_columns)

True

In [24]:
data3 [['TotRmsAbvGrd','Fireplaces']]

      TotRmsAbvGrd  Fireplaces
0                5           0
1                6           0
2                6           1
3                7           1
4                5           0
...            ...         ...
1454             5           0
1455             6           0
1456             7           1
1457             6           0
1458             9           1

[1459 rows x 2 columns]

In [25]:
data3 = data3[X2_columns]
data3

,MSSubClass,LotFrontage,LotArea,OverallQual,OverallCond,YearBuilt,YearRemodAdd,MasVnrArea,BsmtFinSF1,BsmtFinSF2,...,SaleType_ConLw,SaleType_New,SaleType_Oth,SaleType_WD,SaleCondition_Abnorml,SaleCondition_AdjLand,SaleCondition_Alloca,SaleCondition_Family,SaleCondition_Normal,SaleCondition_Partial
0,20,80.0,11622,5,6,1961,1961,0.0,468.0,144.0,...,False,False,False,True,False,False,False,False,True,False
1,20,81.0,14267,6,6,1958,1958,108.0,923.0,0.0,...,False,False,False,True,False,False,False,False,True,False
2,60,74.0,13830,5,5,1997,1998,0.0,791.0,0.0,...,False,False,False,True,False,False,False,False,True,False
3,60,78.0,9978,6,6,1998,1998,20.0,602.0,0.0,...,False,False,False,True,False,False,False,False,True,False
4,120,43.0,5005,8,5,1992,1992,0.0,263.0,0.0,...,False,False,False,True,False,False,False,False,True,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1454,160,21.0,1936,4,7,1970,1970,0.0,0.0,0.0,...,False,False,False,True,False,False,False,False,True,False
1455,160,21.0,1894,4,5,1970,1970,0.0,252.0,0.0,...,False,False,False,True,True,False,False,False,False,False
1456,20,160.0,20000,5,7,1960,1996,0.0,1224.0,0.0,...,False,False,False,True,True,False,False,False,False,False
1457,85,62.0,10441,5,5,1992,1992,0.0,337.0,0.0,...,False,False,False,True,False,False,False,False,True,False
1458,60,74.0,9627,7,5,1993,1994,94.0,758.0,0.0,...,False,False,False,True,False,False,False,False,True,False

In [26]:
rs2 = joblib.load("./model/robust_scaler_xgb.joblib")
data3_scaled = rs2.transform(data3)
data3_scaled = pd.DataFrame(data3_scaled, columns=data3.columns)
data3_scaled

,MSSubClass,LotFrontage,LotArea,OverallQual,OverallCond,YearBuilt,YearRemodAdd,MasVnrArea,BsmtFinSF1,BsmtFinSF2,...,SaleType_ConLw,SaleType_New,SaleType_Oth,SaleType_WD,SaleCondition_Abnorml,SaleCondition_AdjLand,SaleCondition_Alloca,SaleCondition_Family,SaleCondition_Normal,SaleCondition_Partial
0,-0.6,0.578947,0.529521,-0.5,1.0,-0.260870,-0.891892,0.000000,0.118638,144.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
1,-0.6,0.631579,1.182930,0.0,1.0,-0.326087,-0.972973,0.657534,0.757459,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
2,0.2,0.263158,1.074975,-0.5,0.0,0.521739,0.108108,0.000000,0.572131,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
3,0.2,0.473684,0.123394,0.0,1.0,0.543478,0.108108,0.121766,0.306774,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
4,1.4,-1.368421,-1.105114,1.0,0.0,0.413043,-0.054054,0.000000,-0.169182,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1454,2.2,-2.526316,-1.863266,-1.0,2.0,-0.065217,-0.648649,0.000000,-0.538435,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
1455,2.2,-2.526316,-1.873641,-1.0,0.0,-0.065217,-0.648649,0.000000,-0.184626,0.0,...,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,-1.0,0.0
1456,-0.6,4.789474,2.599185,-0.5,2.0,-0.282609,0.054054,0.000000,1.180063,0.0,...,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,-1.0,0.0
1457,0.7,-0.368421,0.237772,-0.5,0.0,0.413043,-0.054054,0.000000,-0.065286,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
1458,0.2,0.263158,0.036685,0.5,0.0,0.434783,0.000000,0.572298,0.525799,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0

In [32]:
[data3_scaled.iloc[0]]

[MSSubClass              -0.600000
 LotFrontage              0.578947
 LotArea                  0.529521
 OverallQual             -0.500000
 OverallCond              1.000000
                            ...
 SaleCondition_AdjLand    0.000000
 SaleCondition_Alloca     0.000000
 SaleCondition_Family     0.000000
 SaleCondition_Normal     0.000000
 SaleCondition_Partial    0.000000
 Name: 0, Length: 266, dtype: float64]

In [33]:
xgbr = joblib.load("./model/xgbr_model.joblib")
pred = xgbr.predict([data3_scaled.iloc[0]])
pred = pd.DataFrame(pred)
pred

               0
0  125822.539062

# joblib으로 저장한 scaler, model 불러오기

In [6]:
import joblib

In [7]:
robust_scaler = joblib.load("./model/iowa_robustscaler.joblib")

In [18]:
data2_scaled = robust_scaler.transform(data2_selected)
data2_scaled = pd.DataFrame(data2_scaled, columns=data2_selected.columns)
data2_scaled

,OverallQual,GrLivArea,GarageCars,YearBuilt,FullBath,TotalBsmtSF,1stFlrSF,ExterQual_Gd,YearRemodAdd,Fireplaces,KitchenQual_TA,GarageFinish_Unf,ExterQual_TA
0,-0.5,-0.877559,-1.0,-0.260870,-1.0,-0.217910,-0.375061,0.0,-0.891892,-1.0,0.0,1.0,0.0
1,0.0,-0.208575,-1.0,-0.326087,-1.0,0.671642,0.475209,0.0,-0.972973,-1.0,-1.0,1.0,0.0
2,-0.5,0.254925,0.0,0.521739,0.0,-0.126368,-0.312224,0.0,0.108108,0.0,0.0,0.0,0.0
3,0.0,0.216300,0.0,0.543478,0.0,-0.130348,-0.316151,0.0,0.108108,0.0,-1.0,0.0,0.0
4,1.0,-0.284280,0.0,0.413043,0.0,0.574129,0.378989,1.0,-0.054054,-1.0,-1.0,0.0,-1.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...
1454,-1.0,-0.574739,-2.0,-0.065217,-1.0,-0.886567,-1.062347,0.0,-0.648649,-1.0,0.0,0.0,0.0
1455,-1.0,-0.574739,-1.0,-0.065217,-1.0,-0.886567,-1.062347,0.0,-0.648649,-1.0,0.0,1.0,0.0
1456,-0.5,-0.370800,0.0,-0.282609,-1.0,0.462687,0.269023,0.0,0.054054,0.0,0.0,1.0,0.0
1457,-0.5,-0.763229,-2.0,0.413043,-1.0,-0.158209,-0.229750,0.0,-0.054054,-1.0,0.0,0.0,0.0
1458,0.5,0.828119,1.0,0.434783,0.0,0.008955,-0.178694,0.0,0.000000,0.0,0.0,0.0,0.0

In [20]:
def data_preprocessing(data):
    data=pd.get_dummies(data)
    data = data[['OverallQual', 'GrLivArea', 'GarageCars', 'YearBuilt', 'FullBath',
       'TotalBsmtSF', '1stFlrSF', 'ExterQual_Gd', 'YearRemodAdd', 'Fireplaces',
       'KitchenQual_TA', 'GarageFinish_Unf', 'ExterQual_TA']]
    rs = robust_scaler = joblib.load("./model/iowa_robustscaler.joblib")
    data_scaled = rs.transform(data)
    data_scaled = pd.DataFrame(data_scaled, columns=data.columns)
    return data_scaled

In [21]:
test_data = data_preprocessing(data)

In [3]:
from tensorflow.keras.models import load_model

In [4]:
model = load_model("./model/iowa_house792__925173184.0000.keras")

2024-09-11 15:06:11.518778: I tensorflow/core/platform/cpu_feature_guard.cc:193] This TensorFlow binary is optimized with oneAPI Deep Neural Network Library (oneDNN) to use the following CPU instructions in performance-critical operations:  AVX2 FMA
To enable them in other operations, rebuild TensorFlow with the appropriate compiler flags.
2024-09-11 15:06:11.520542: I tensorflow/c/logging.cc:34] DirectML: creating device on adapter 0 (AMD Radeon(TM) RX Vega 11 Graphics)
2024-09-11 15:06:11.618749: I tensorflow/core/common_runtime/pluggable_device/pluggable_device_factory.cc:306] Could not identify NUMA node of platform GPU ID 0, defaulting to 0. Your kernel may not have been built with NUMA support.
2024-09-11 15:06:11.618799: W tensorflow/core/common_runtime/pluggable_device/pluggable_device_bfc_allocator.cc:28] Overriding allow_growth setting because force_memory_growth was requested by the device.
2024-09-11 15:06:11.618824: I tensorflow/core/common_runtime/pluggable_device/pluggable_device_factory.cc:272] Created TensorFlow device (/job:localhost/replica:0/task:0/device:GPU:0 with 15603 MB memory) -> physical PluggableDevice (device: 0, name: DML, pci bus id: <undefined>)

In [27]:
test_pred = model.predict(test_data)
test_pred = pd.DataFrame(test_pred, columns=["test_pred"])

46/46 [==============================] - 0s 4ms/step

In [28]:
test_pred

          test_pred
0     109955.562500
1     146410.140625
2     167009.890625
3     195284.078125
4     200004.109375
...             ...
1454  113808.890625
1455  108089.812500
1456  139701.765625
1457  128684.101562
1458  239234.031250

[1459 rows x 1 columns]

In [19]:
from sklearn.preprocessing import MinMaxScaler
import numpy as np

# 첫 번째 경우: 1과 10000
data1 = np.array([[1], [5000], [10000]])
scaler1 = MinMaxScaler()
scaled_data1 = scaler1.fit_transform(data1)

# 두 번째 경우: 1과 100000
data2 = np.array([[1], [50000], [100000]])
scaler2 = MinMaxScaler()
scaled_data2 = scaler2.fit_transform(data2)

print("1과 10000을 변환한 결과:")
print(scaled_data1)

print("\n1과 100000을 변환한 결과:")
print(scaled_data2)

1과 10000을 변환한 결과:
[[0.        ]
 [0.49994999]
 [1.        ]]

1과 100000을 변환한 결과:
[[0.      ]
 [0.499995]
 [1.      ]]